### ISSUE TITLE
Invalid Eradiate results on a white Lambertian surface

### ISSUE THREAD

**Issue by wint3ria** [eradiate/eradiate#173]
# Is this the bug we deserve?

## Summary

It may be related to [this mitsuba issue](https://github.com/mitsuba-renderer/mitsuba2/issues/171), AKA the *batman bug*
My Eradiate results seem a bit off on a simple white lambertian surface for some specific viewing geometries

![2022-02-15-134905_597x479_scrot](https://user-images.githubusercontent.com/10501833/154065322-b2cc7825-7c9f-42e8-a09f-7705fe50be34.png)

![2022-02-15-134920_592x483_scrot](https://user-images.githubusercontent.com/10501833/154065425-ffc5e8c6-df57-4ed8-b0bc-7aade2c1526a.png)

This can have a significant impact on Eradiate bias wrt other models

## Description

The scene is a very simple scattering only (or Rayleigh) atmosphere on top of a white lambertian surface.
The results around vza=0 are quite far from the expected value.

I'm still not sure the problem does not come from my Eradiate config, since I'm refactoring a big part of my code.
However, I can not find any problem even after reviewing the config several times. **May I ask a double check?**
**I may have missed something while plotting the results?**

Correct me if I'm wrong, but the *batman bug* generally produces results with a BRF exactly equal to the surface reflectance. It's not the case here.

I tried different SPP values, up to 10000. It does not look like a noise issue.

## Configuration file

[The exact configuration I'm using is available here](https://gist.github.com/wint3ria/4a86bb8b458427e2b6430c8ecc2e77c6)

## Steps to reproduce

Assuming you downloaded the configuration file in local, here is a simple python code to reproduce my computations

```python
import json
import eradiate
eradiate.set_mode("ckd_double")

with open("white_scattering_config.json") as f:
    config = json.load(f)
    experiment = eradiate.experiments.Rami4ATMExperiment(**config)
    experiment.run()
    ds = experiment.results["pipeline_measure"]
    ds.squeeze().brf.plot()
    ds.squeeze().mean(dim="w").brf.plot()
```

## System configuration

- Operating system: `Linux fenrir 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 x86_64 x86_64 GNU/LinuxGNU/Linux`
- Compiler: clang-9
- Python version: `Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
[GCC 9.4.0] on linux`
- Eradiate version: from commit f83994c

![2022-02-15-115701_597x399_scrot](https://user-images.githubusercontent.com/10501833/154065532-06d69107-0550-4aa0-89a1-4354282b8568.png)

**Comment by leroyvn** [comment]
Hi @wint3ria, thanks for reporting this. I actually suspect that this is due to problematic volume data indexing on our end. I'll try and run your sample code with a little kernel update and fixes to the indexing, I'll let you know about my findings.

**Comment by wint3ria** [comment]
Thanks Vincent. FYI it's the first rami4atm test case. If the config is correct, then I may be ready to generate more configs for the Eradiate CI

**Comment by leroyvn** [comment]
After a check, it's very likely that the ordering of your viewing angle specification is not what you would expect: you're declaring zeniths from 0° to 75°, first for the 0° azimuth half plane, then from the 180° half plane: (0°, 0°) to (75°, 0°) then (0°, 180°) to (75°, 180°). I assume you would expect a coverage from (75°, 180°) to (0°, 180°) then (0°, 0°) to (75°, 0°).

That would explain the stitch in the middle as well as a wrong orientation, if any. That being said, a few issues are being fixed on the `its_not_flat` branch, which I expect to merge in the coming days into `next`. Those issues might also negatively impact the quality of your results.
