### ISSUE TITLE
 Building CXX object bilambertian.cpp.o fails: "call to 'abs' is ambiguous"

### ISSUE THREAD

**Issue by fehr-t** [eradiate/eradiate#216]
# Bug report

## Summary

When building Eradaite the following the process stops with the following error message:

```
[2/3] Building CXX object src/plugins/src/bsdfs/CMakeFiles/bilambertian.dir/bilambertian.cpp.o
FAILED: src/plugins/src/bsdfs/CMakeFiles/bilambertian.dir/bilambertian.cpp.o
../src/plugins/src/bsdfs/bilambertian.cpp:154:47: error: call to 'abs' is ambiguous

```

## Description

Complete error log is attached,
[Eradiate_Build_error.log](https://github.com/eradiate/eradiate/files/8528349/Eradiate_Build_error.log)

together with the preset output.
[Eradiate_Build_error.log](https://github.com/eradiate/eradiate/files/8528351/Eradiate_Build_error.log)

## Steps to reproduce

Error os produced during the build `cmake --build build` commando

## System configuration

*Please provide information regarding your system configuration*

- Operating system: MacOS 10.15.7
- Compiler: ...
- Python version: 2.7.16
- Eradiate version: Most recent Git clone

**Comment by leroyvn** [comment]
Hi @fehr-t, in order to better diagnose your issue, can you provide the compiler version you are using? You should get it by invoking `clang --version` from the terminal.

I also notice that you mention using Python 2.7. Eradiate requires Python 3.8 or later: did you set up and activate a Conda environment prior to building Mitsuba?

**Comment by fehr-t** [comment]
Hey @leroyvn, 

I was updating all my routines and starte4d recompiling Eradiate, bu t with basically the same error att the end/.

Below the Clang version:

```
clang --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Concerning Python and Conda

```
est01103604:eradiate tfehr$ which python
/Users/tfehr/opt/miniconda3/envs/eradiate/bin/python
(eradiate) est01103604:eradiate tfehr$ python -V
Python 3.8.12
```

I hope this helps tracking the issue.

**Comment by leroyvn** [comment]
Hi Thorsten, I found an issue indeed. Please try and replace line 154 in file `src/plugins/src/bsdfs/bilambertian.cpp`:

```diff
- result[active] *= (dr::InvPi<Float> * abs(cos_theta_o));
+ result[active] *= (dr::InvPi<Float> * dr::abs(cos_theta_o));
```

and line 174

```diff
- Vector3f wo_flip{ wo.x(), wo.y(), abs(cos_theta_o) };
+ Vector3f wo_flip{ wo.x(), wo.y(), dr::abs(cos_theta_o) };
```

**Comment by fehr-t** [comment]
Hey Vincent,

this seems to have solved the problem. 
`eradiate show` producers the following message which I interpret as Eradiate successfully installed.

```
───────────────────────────────────────────────────────────────────────────────────────────────────────────────── Version ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────
• eradiate 0.22.2.post1
────────────────────────────────────────────────────────────────────────────────────────────────────────────── Configuration ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
• ERADIATE_SOURCE_DIR: /Users/tfehr/Software/eradiate
• ERADIATE_DATA_PATH: None
• ERADIATE_DATA_STORE_URL: http://eradiate.eu/data/store/
• ERADIATE_DOWNLOAD_DIR: /Users/tfehr/Software/eradiate/resources/downloads
• ERADIATE_PROGRESS: 2
────────────────────────────────────────────────────────────────────────────────────────────────────────────── Path resolver ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
• /Users/tfehr/Software/eradiate [current]
• /Users/tfehr/Software/eradiate/resources/data

```

**Comment by leroyvn** [comment]
Good! We will roll out this update in the next release. I'll close this issue.
