### ISSUE TITLE
[BUG] Run Eradiate with Docker Desktop

### ISSUE THREAD

**Issue by gritk** [eradiate/eradiate#257]
# Bug report

## Summary

run Eradiate with Docker Desktop & Kernel died 

## Description

Unfortunately, I am not able to run the examples given in the tutorials. After the command "import eradiate" the kernel died, and no computation has been started - see image attached

## Steps to reproduce
1. Run Docker desktop
2. Paste this command into a terminal: docker run -p "8888:8888" --rm -it rayference/eradiate-jupyterlab
3. Open container with server and insert the token
4. Run parts of canopy2_tutorial

## System configuration

- Operating system: Windows 10 Professional & Docker Desktop  4.10.1 (82475)

image: ![issue_eradiate_docker](https://user-images.githubusercontent.com/686225/186447226-649abcf9-374c-497c-82f9-2c33a311b658.png)

**Comment by leroyvn** [comment]
Hi @gritk, thanks for reporting this.

The Docker image build process is currently out of date. The latest image build is [v0.22.2](https://github.com/eradiate/eradiate/tree/v0.21.2), released several months ago, and Eradiate got many improvements and fixes since then. Unfortunately, we don't have the resources for an update at the moment.

Until this is fixed, we advise all users to use Eradiate without Docker. We run it routinely on WSL2 on Windows 11, and this works very well. We will also prioritise the upgrade of the Docker build based on user feedback and requests.

**Comment by wint3ria** [comment]
@gritk , I am able to reproduce a very similar behavior on my machine. The docker image available on docker hub has the support for AVX512 enabled. My CPU does not support this instruction set, hence the SIGILL and the silent crash. The first conclusion is that these images require AVX512 support.

You can check if your CPU proposes this instruction by greping the CPU feature flag in /proc/cpuinfo on Linux:

```
$ cat /proc/cpuinfo | grep avx512 | wc -l
> 0
```

In my case I count 0 occurrence of this flag, thus my CPU+OS are not compatible. I don't know how to check this on Windows however.

Can you double check that your problem also occurs when only using the docker version of Mitsuba?

``` bash
$ docker run -it rayference/eradiate-kernel
> ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['/bin/bash', '-c', 'mitsuba --help']' command failed.  (See above for error)
> /opt/conda/envs/docker/.tmpo3byvxrq: line 3:    17 Illegal instruction     (core dumped) /bin/bash -c "mitsuba --help"
```

If you obtain a similar output, then you can check the instruction causing the crash using gdb. It could ensure that you are running into the same problem. First install gdb on a `rayference/eradiate` based container, and run it against mitsuba:

``` bash
$ docker run -it rayference/eradiate bash
$ apt update && apt install gdb
$ gdb -q mitsuba
> Reading symbols from mitsuba...
> (No debugging symbols found in mitsuba)
```

Then you can run the mitsuba program in gdb and let it bump into the illegal instruction:

```
(gdb) run
> Starting program: /mitsuba/dist/mitsuba 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

> Program received signal SIGILL, Illegal instruction.
> 0x00007fc1c634b3f4 in _GLOBAL__sub_I_pugixml.cpp () from /mitsuba/dist/libpugixml.so
```

From there you can look the backtrace. Providing this log output would be helpful for us:

```
(gdb) bt
> #0  0x00007fc1c634b3f4 in _GLOBAL__sub_I_pugixml.cpp () from /mitsuba/dist/libpugixml.so
> #1  0x00007fc1c6b99b9a in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7ffea7030ea8, env=env@entry=0x7ffea7030eb8) at dl-init.c:72
> #2  0x00007fc1c6b99ca1 in call_init (env=0x7ffea7030eb8, argv=0x7ffea7030ea8, argc=1, 
    l=<optimized out>) at dl-init.c:30
> #3  _dl_init (main_map=0x7fc1c6bb7190, argc=1, argv=0x7ffea7030ea8, env=0x7ffea7030eb8)
    at dl-init.c:119
> #4  0x00007fc1c6b8913a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
> #5  0x0000000000000001 in ?? ()
> #6  0x00007ffea70316d7 in ?? ()
> #7  0x0000000000000000 in ?? ()
```

Last step is to look for the actual CPU instruction causing the crash. You can do that in gdb using the following:

```
(gdb) display/i $pc
> 1: x/i $pc
> => 0x7fc1c634b3f4 <_GLOBAL__sub_I_pugixml.cpp+36>:	vpbroadcastq %rax,%xmm0
```

This `vpbroadcastq` instruction is part of AVX512 instruction set, as mentioned in the [Intel doc](https://hjlebbink.github.io/x86doc/html/VPBROADCASTB_W_D_Q.html). 

If you could try to reproduce the above, it would help immensely :pray:

**Comment by gritk** [comment]
@wint3ria @
Dear Nicolas,

I have tried to answer your questions, 

               Reply on your question: Can I ask you the following information, so that I can try to investigate further?

![grafik](https://user-images.githubusercontent.com/686225/186958771-e0059f40-e7ab-40d7-bddf-262b78c7415c.png)
![grafik](https://user-images.githubusercontent.com/686225/186958875-6429e4f2-148d-437a-aa29-d0b9dbd2e13a.png)


                 Reply on your question: Can you double check that your problem also occurs when only using the docker version of Mitsuba?

![grafik](https://user-images.githubusercontent.com/686225/186959481-f0c59992-650c-4799-8b57-625677a0f8bd.png)

At the moment I have stopped here and will do the other steps as soon as possible.

Many thanks for this,
Grit

**Comment by gritk** [comment]
Dear Nicolas,

I followed your instructions and received the following: 

```
(docker) root@317dc82054bd:/app# gdb -q mitsuba
Reading symbols from mitsuba...
(No debugging symbols found in mitsuba)

(gdb) run
Starting program: /mitsuba/dist/mitsuba
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x00007f4b756ef3f4 in _GLOBAL__sub_I_pugixml.cpp () from /mitsuba/dist/libpugixml.so

(gdb) bt
#0  0x00007f4b756ef3f4 in _GLOBAL__sub_I_pugixml.cpp () from /mitsuba/dist/libpugixml.so
#1  0x00007f4b75f3db9a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffbb523e38, env=env@entry=0x7fffbb523e48) at dl-init.c:72
#2  0x00007f4b75f3dca1 in call_init (env=0x7fffbb523e48, argv=0x7fffbb523e38, argc=1, l=<optimized out>) at dl-init.c:30
#3  _dl_init (main_map=0x7f4b75f5b190, argc=1, argv=0x7fffbb523e38, env=0x7fffbb523e48) at dl-init.c:119
#4  0x00007f4b75f2d13a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#5  0x0000000000000001 in ?? ()
#6  0x00007fffbb5256d6 in ?? ()
#7  0x0000000000000000 in ?? ()

(gdb) display/i $pc
1: x/i $pc
=> 0x7f4b756ef3f4 <_GLOBAL__sub_I_pugixml.cpp+36>:      vpbroadcastq %rax,%xmm0`
```

Kind regards, 
Grit

**Comment by wint3ria** [comment]
@gritk The problem is definitely that your CPU does not support AVX512. We are currently brainstorming a way to handle the different compiled versions of Mitsuba that we need. I may come back with updates later in the following weeks. I hope you can run Eradiate for your needs using the standard workflow. Let us know if you need any help in that regard, in another issue perhaps

**Comment by wint3ria** [comment]
Hello @gritk , I'm was happy to see on other issues that you managed to build Mitsuba.

Concerning Docker: it has been decided to drop the support for now, a patch will come eventually. A part of the current developments on Eradiate include some refactoring of the packaging and dependencies handling. Binaries for the Eradiate kernel shall be provided through a setuptools based installation, not Docker. Future developments may include new Docker images, but this work will be performed outside of the main Eradiate project, and no planning is foreseen yet.

The build process of the Mitsuba variant for Eradiate depends on the Mitsuba workflow for now
