### ISSUE TITLE
Implement a process level locking mechanism to safely run eradiate in a multi-threaded context

### ISSUE THREAD

**Issue by wint3ria** [eradiate/eradiate#290]
# Feature request

## Summary

The eradiate data module does not implement any locking mechanism. This seems to be problematic when having several instances of Eradiate accessing the filesystem through xarray concurrently from different threads. I observed this behavior while using dask for distributed computations. Dask workers may be multi threaded, yet eradiate shall not run in a multi threaded context. Support of this setup has not been foreseen and I doubt we actually want to implement it. Mutli-threaded should be left to Mitsuba in our context. 

However, Dask does not allow to set the max number of concurrent tasks on a worker. Limiting the number of threads in dask puts a hard limit on the CPU resources a worker has access to. As a result, a dask worker run one task at a time, or has access to multiple threads for Mitsuba computations. This is a serious limitation.

On top of this, concurrent access errors are difficult to debug, especially in a distributed setup.

## Reason and benefit

This request describes the implementation of a process level locking mechanism in Eradiate, to solve the mentioned issues by:

- Protecting some clear critical sections in the eradiate data module
- Protecting the multi-threaded parts of eradiate as a critical section, since it is not suitable to have several mitsuba instances running from different python level threads.
- Provide multi-threaded execution handling facilities to easily
  - handle any potential critical section
  - assess the number of python threads in the current process and adapt the behavior accordingly
  - reproduce the mentioned issues in regression tests
  - activate/configure/deactivate the locking mechanisms for each critical section
  - help avoiding deadlocks

## Details

A separated module should be implemented to handle the logic. I would call it `locks`, and place it at `src/eradiate/locks.py`. This is a suggestion that may be moved and renamed to anything more suitable. The default behavior should be defined using the eradiate.config facility

### User interface

Concerning the interface, @leroyvn suggested a contextual implementation. I would call the context manager `protect`. This context manager would allow to specifically activate some categories of critical sections:

```python
# Use default locking behavior (protect everything?)
experiment = eradiate.scenes.experiments.AtmosphereExperiment(...)
eradiate.run(experiment)

# Protect the eradiate data and mitsuba run critical section categories
with eradiate.protect(categories=["data", "run"]):
    experiment = eradiate.scenes.experiments.AtmosphereExperiment(...)
    eradiate.run(experiment)

# Protect the eradiate data critical section category only
with eradiate.protect(categories=["data"]):
    experiment = eradiate.scenes.experiments.AtmosphereExperiment(...)
    eradiate.run(experiment)
```
### Developers interface

As already mentioned, a critical section would be listed in a category. For instance, the eradiate.data module would implement a critical section per dataset, each of which would be listed in the "data" category.

I suggest to use a combination of a context manager and a python decorators to provide eradiate developers with convenient ways to declare critical sections.

```python
with eradiate.locks.declare(category="data", name="sentinel_2a-msi-8a.nc"):
    # critical section start
    ...
    xr.open_dataset(...)
    ...
    # critical section end
# not critical
```
or:
```python
class DummyExample:
    ...
    @eradiate.locks.declare(category="data") # the function/method name could be used for this use case
    def method_with_critical_section(self):
        # critical section start
        ...
        xr.open_dataset(...)
        ...
        # critical section end
```

The decorator would simply use the context manager internally. Here is a rough implementation sketch:

```python
class CriticalSection:
    ...
    def __enter__(self, category, name):
         ... # filter activated categories using the configuration
         self.locks[category][name].acquire()

    def __exit__(self):
        ...
        self.locks[category][name].unlock()

    def __call__(self, func, category):
        def wrapped(*args, **kwargs):
            with self(category, func.__name__):
                return func(*args, **kwargs)
        return wrapped

eradiate.locks.declare = CriticalSection()
```

### Configuration

A `locks` attribute could be added to `eradiate.config` as a mapping, providing the boolean `activated` entry and a set of default protected critical section names entry called `sections`. The eradiate.protect context manager would then simply change the config.

```python
eradiate.config.locks
> { "activated": True, "sections": { "data" } }
```

Default behavior should be decided. I advocate for at least protecting the eradiate data critical sections by default.

### Additional features

The module could detect mutlti-threaded instances and issue warnings when critical sections are not protected

Some inspection features should be provided in order to list the critical sections with their statuses

This locking mechanism needs to be tested to work with dask workers multi-threading

### Testing

This is an issue. I do not see how I can reproduce the concurrent access issues I have with a 100% chance. The best test I can think of for now would be *likely* to reproduce the errors I faced when opening several CKD datasets. The implemented critical sections would ensure that these never fail, but if the locks module was improperly used/implemented, we would end up with tests that *could* detect the issue

**Comment by leroyvn** [comment]
Hi @wint3ria, could [this issue](https://github.com/pydata/xarray/issues/4100) be related with what you're experiencing?

**Comment by wint3ria** [comment]
It's very possible. It further confirms the need for a thread safety mechanism in Eradiate. From what I understand Xarray open_dataset is not thread safe. The data loaded after open_dataset is thread safe. Having a custom thread-safe HDF5 version for our use case is a no-go for me. If we were to ship some binary, the priority would be on packaging Mitsuba. I also believe locking could be used somewhere else if required in the future. Thread safety for open_dataset seems to be an open discussion topic in the design of xarray. Discussions are already 2 years old, and I doubt we'll have a thread-safe implementation coming from the xarray team in the short term. It's not even sure they want to implement one

**Comment by wint3ria** [comment]
After further research, it appears support for thread safe in HDF5 (dependency of the default backend for netcdf) [needs to be recompiled with specific options in order to be thread safe](https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access). Other file format backends such as zarr or netcdf3 may provide thread safety without the need to recompile anything. I don't think we want to change the file format however. Hence a couple of questions:
- We intend to provide binary packages for our version of mitsuba; would it be acceptable to maintain a compiled version of HDF5 too? In that case, we could just provide the thread-safe binary. It would only solve thread-safety issues in xarray + netcdf4 though.
- We can handle thread safety inside the eradiate python code, but there are two ways of proceeding : [write a thread safe backend that we would inject in xarray](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html), or write a more general framework to handle critical sections in Eradiate, similar to what I described earlier in this issue. I believe the later can be done directly in the main Eradiate codebase repository. Writing another xarray backend seems to be a good candidate for an external python module. The backend option thus limits the amount of code to write inside of eradiate, but it only solve issues we may face regarding multi-threading in xarray for netcdf4 files, thus limiting the scope.

**Comment by wint3ria** [comment]
After further research, it appears support for thread safe in hdf5 [needs to be recompiled with specific options in order to be thread safe](https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access). Other file format backends such as zarr or netcdf3 may provide thread safety without the need to recompile anything. I don't think we want to change the file format however. Hence a couple of questions:

    We intend to provide binary packages for our version of mitsuba; would it be acceptable to maintain a compiled version of HDF5 too? In that case, we could just provide the thread-safe binary. It would only solve thread-safety issues in xarray + netcdf4 though.
    We can handle thread safety inside the eradiate python code, but there are two ways of proceeding : [write a thread safe backend that we would inject in xarray](https://docs.xarray.dev/en/stable/internals/how-to-add-new-backend.html), or write a more general framework to handle critical sections in Eradiate, similar to what I described earlier in this issue. I believe the later can be done directly in the main Eradiate codebase repository. Writing another xarray backend seems to be a good candidate for an external python module. The backend option thus limits the amount of code to write inside of eradiate, but it only solve issues we may face regarding multi-threading in xarray for netcdf4 files, thus limiting the scope.

**Comment by leroyvn** [comment]
I'm not much of a fan of providing custom binaries for such fundamental parts of the Scipy stack: the goal is, eventually, to allow for a drop-in install in a user-defined environment. I find the Python fix approach safer in that regard.

A general critical section system could be nice if there would be a use case behind it: I'd like to avoid embarking in providing yet another general feature which will be used just once. Actually, if this goes beyond just fixing threading issues during xarray loading, I'd even prefer this component to be written as a lib we could then reuse in other projects (if possible/relevant).

So as a wrap-up: if there is currently nothing else to fix, an optional custom thread-safe NetCDF backend is my favourite (plus, this way, people not using Eradiate in a threaded environment can still use the original backend or any other they like).

**Comment by wint3ria** [comment]
Unless the need for a safer thread level parallelism arise again, I close this issue, for which the solution (writing a netCDF backend) is out of the scope.
