### ISSUE TITLE
Simple experiment produces zero radiance with Apple M2 CPU [BUG] 

### ISSUE THREAD

**Issue by nollety** [eradiate/eradiate#339]
# Bug report

## Summary

I am creating this issue to report a bug that occurs on Apple M2 CPU (initially reported by @Srheft in #332).

## Description

It seems that although Eradiate can be successfully installed on a system with an Apple M2 CPU, a simple experiment  such as the experiment that is created in the [First steps with Eradiate](https://eradiate.readthedocs.io/en/latest/tutorials/getting_started/eradiate_quickstart.html) tutorial,  produces incorrect results ; the radiance values are zero.

## Steps to reproduce

Run the [First steps with Eradiate](https://eradiate.readthedocs.io/en/latest/tutorials/getting_started/eradiate_quickstart.html) tutorial.

## System configuration

```
── System ──────
CPU: b'Apple M2 Pro'
OS: 13.4
Python: 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:05:36) [Clang 14.0.6 ]
── Versions ─────────
• eradiate 0.23.1.post1.dev26+g9a3bdcee
• drjit 0.4.1
• mitsuba 3.2.1
── Available Mitsuba variants ──
• scalar_mono
• scalar_mono_double
• scalar_rgb
• scalar_spectral
• llvm_mono_double
• llvm_ad_rgb
── Configuration ─────────
• ERADIATE_AZIMUTH_CONVENTION: AzimuthConvention.EAST_RIGHT
• ERADIATE_DATA_STORE_URL: http://eradiate.eu/data/store/
• ERADIATE_DOWNLOAD_DIR: /Users/seftekh1/eradiate/resources/downloads
• ERADIATE_OFFLINE: False
• ERADIATE_PROGRESS: ProgressLevel.KERNEL (2)
• ERADIATE_SOURCE_DIR: /Users/seftekh1/eradiate
```

**Comment by wint3ria** [comment]
M1 support is here. It's not the M2, ofc, but we could try to do some tests maybe? We could also try to have a self hosted M2 runner somewhere?

**Comment by leroyvn** [comment]
I'll close since we haven't had reports about this in a long time. We'll reopen if necessary
