### ISSUE TITLE
Cannot configure CMake for compilation

### ISSUE THREAD

**Issue by SylvainDoute** [eradiate/eradiate#348]
# Bug report

## Summary

I cannot configure CMake for compilation with the requested command `cmake --preset default`

## Description

Following the installation procedure for the mac, I reached the compilation step for the radiometric kernel. Everything went well up to this point. I am in the main eradiate directory. Trying to configure CMake for the compilation with the requested command `cmake --preset default` returns an error 

```
CMake Error: Could not read presets from xxx/xxx/xxx/eradiate: File not found
```

## Steps to reproduce

*Please enumerate the steps to follow in order to reproduce the issue. If possible, please provide a minimal reproducible example.*

1. `cd eradiate`
2. `cmake --preset default`

The only preset file cmake will understand is in eradiate/ext/mitsuba/
when typing cmake --preset eradiate
it returns 
```
  CMAKE_BUILD_TYPE="Release"
  MI_DEFAULT_VARIANTS="scalar_mono;scalar_mono_double;scalar_rgb;scalar_spectral;llvm_rgb"
  MI_ENABLE_EMBREE="OFF"

-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:60 (message):
  In-tree builds are not permitted.  To recover, delete 'CMakeCache.txt', the
  'CMakeFiles' directory and inform CMake about the source (-S) and build
  (-B) paths.  For example to compile to a directory labeled 'build' using
  the Ninja generator, enter

    $ rm -Rf CMakeCache.txt CMakeFiles
    $ cmake -S . -B build -G Ninja
    $ cmake --build build


-- Configuring incomplete, errors occurred!
```

## System configuration

*Please provide information regarding your system configuration*

- Operating system: Mac OS 10.15.7
- Compiler: Apple clang version 12.0.0 (clang-1200.0.32.21)
- Python version: Python 3.8.17
- Eradiate version: v0.23.1
-  cmake version 3.26.4

Thank you very much in advance for your help.

**Comment by leroyvn** [comment]
Hello @SylvainDoute, thank you for this report. We very recently reorganized our codebase and modified developer installation instructions a bit. Just to be sure, I'd like to check on which Git ref you are. Could you run `git rev-parse --short HEAD` and give me the result?

**Comment by SylvainDoute** [comment]
Hello Vincent, thank you for addressing my problem.
The result is : 
git rev-parse --short HEAD
34991379

**Comment by SylvainDoute** [comment]
I managed to successfully build the radiometric kernel. 
I am looking forward to use it and test it with a particular attention to the generation of the path radiance (looking down from space), the diffuse illumination at the ground looking up and other transfer functions ... We will use our own aerosols and maybe our own k-correlated coefficients (I have to look at the documentation if it is possible).
I will do it this summer with an internship student. We will try to write a little report.
Thank you Vincent.
Have a good summer !

**Comment by leroyvn** [comment]
Thanks, you too!
