### ISSUE TITLE
[BUG] Installation fails under Windows

### ISSUE THREAD

**Issue by gritk** [eradiate/eradiate#371]
# Bug report

## Summary

_**Installation fails under Windows**_

"Eradiate is delivered through PyPI and can be installed using the pip. This is the recommended way to install Eradiate."

 * Installation fails under Windows

## Description

```
 pip install eradiate==0.24.3 

  Obtaining dependency information for eradiate==0.24.3 from https://files.pythonhosted.org/packages/55/ab/b0f674af2766b638e5d24ebddd26e4b8173c0805df6891b1e37759af8e1a/eradiate-0.24.3-py3-none-any.whl.metadata
  Using cached eradiate-0.24.3-py3-none-any.whl.metadata (8.4 kB)
INFO: pip is looking at multiple versions of eradiate to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement eradiate-mitsuba==0.0.2 (from eradiate) (from versions: 0.0.1rc5, 0.0.1rc6, 0.0.1rc7, 0.0.1rc8, 0.0.1rc9)
ERROR: No matching distribution found for eradiate-mitsuba==0.0.2
```

## Steps to reproduce

`pip install eradiate==0.24.3` under Windows

## System configuration

- Operating system: Windows 11
- Python version: v3.11
- Eradiate version: v.0.24.3

**Comment by wint3ria** [comment]
Hello @gritk,

Unfortunately, our internal version of the radiometric kernel Mitsuba, packaged as `eradiate-mitsuba` version 0.0.2 is not compiled for Windows. This operating system is not officially supported by our team.

We suggest you to use [Windows Subsystem for Linux (WSL)](https://learn.microsoft.com/en-us/windows/wsl/). We tested it with an Ubuntu 22.04 subsystem and the installation process went well. Please make sure to use the WSL [version 2](https://learn.microsoft.com/fr-fr/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2).

Other solutions exist: you could run a Linux VM, or have a dedicated physical machine running Linux.

Do you have a specific constraint on the OS you can use?

**Comment by gritk** [comment]
Hello,

I have used Eradiate in the Windows Subsystem for Linux (WSL) and in a Linux VM, but would also like to use it directly under Windows. So it would be nice to have support for it under Windows as well.

**Comment by leroyvn** [comment]
Hi @gritk, we now have an experiment Windows package. If you experiment with it, we will appreciate feedback.
