### ISSUE TITLE
Convert spectral radiance into radiance

### ISSUE THREAD

**Issue by Ly0n** [eradiate/eradiate#378]
## Summary
Provide a standard method to convert from spectral radiance into radiance. 

## Reason and benefit
Current simulation results refer to a single wavelength in the form of spectral radiance (W·sr−1·m−2·nm−1). For many applications, however, it is important to integrate these results over a defined bandwidth in order to obtain a total radiance (W·sr−1·m−2) that is visible to a detector within this band. 

## Details

I have an application where I need to model the radiance outside the field of view for an instrument. In combination with a point source transmittance measurement on the ground, this allows me to estimate the out-of-field stray light for various in-orbit scenes. To do this, I have to convert the wavelength-related spectral radiance values into a total radiance for our bandpass filter. I think it would be helpful for different users to implement a tutorial or a standardized method on how to implement this conversion / integral correctly.

**Comment by leroyvn** [comment]
Hi @Ly0n, thanks for bringing up this issue. Indeed, the post-processing pipeline currently doesn't perform SRF weighting for camera-like sensors. This will be addressed soon with the refactoring of these pipelines.

**Comment by leroyvn** [comment]
Hi @Ly0n, the release of the v0.26.x introduces the new flexible post-processing infrastructure I've been talking about. Applying the SRF on an arbitrary spectral radiance dataset is now doable using pipeline components. I added a [tutorial here](https://eradiate.readthedocs.io/en/stable/tutorials/advanced/postprocessing_pipelines.html) to introduce this. I'll close this issue for now, feel free to reopen or open a discussion if you need help setting up your post-processing.

**Comment by Ly0n** [comment]
Thanks @leroyvn! I'm already diving into the new documentation.I just finished the integration of the Point Source Transmission measurements with the Eradaite simulation with great results. You will also get a copy of my PhD thesis when it is finished in about 1 month.
