### ISSUE TITLE
[BUG]  HAPKE BSDF produces invalid values on DEM surfaces

### ISSUE THREAD

**Issue by schunkes** [eradiate/eradiate#391]
# Bug report

## Summary

Using the Hapke BSDF model on a DEM surface produces invalid samples.

## Description

When I use the Hapke BSDF on a flat surface, I get meaningful results. If I attach the BSDF with the same paramters to a DEM surface (50x50km Algeria5 in this case) I get a very large number of invalid values. The number of invalid values varies with the parametrs, but I did not find a configuration, which produces no invalid samples.

Using the RPV BSDF on the same DEM produces zero invalid samples.

## Steps to reproduce

These are the parameters I used.

```python
HapkeBSDF(
    w=0.6,
    h=0.043,
    B_0=0.936,
    theta=14.1,
    b=0.189,
    c=0.452
)
```

**Comment by wint3ria** [comment]
There is a precision issue when ingoing and outgoing vectors are close to colinear in the Hapke implementation. Some usage of the acos function are missing boundary checks. I will write a patch and deliver another release candidate of the kernel by the end of the day.

**Comment by wint3ria** [comment]
BTW the submodule ref in the next branch is outdated, it's pointing to a kernel version for Eradiate 0.25, without Hapke support. I will fix that today, as soon as I have a properly compiled package, and confirmation that the patch I wrote for Hapke fixes the current issue.

**Comment by leroyvn** [comment]
I'll close since we haven't had activity on this for a long time, feel free to reopen if necessary.
