### ISSUE TITLE
Test failure: eradiate/radprops/tests/test_rad_profile.py::test_us76_approx_rad_profile

### ISSUE THREAD

**Issue by wint3ria** [eradiate/eradiate#54]
# Bug report

## Summary

The test_rad_profile.py fails with an HDF error which look like a file format issue.

## Description

I had this issue on both the testing docker container and my development environment
Please find attached the output log of pytest

[test-logs.txt](https://github.com/eradiate/eradiate/files/6199272/test-logs.txt)

## Steps to reproduce

You simply need to run `pytest eradiate` in the source folder. The additional datasets for Eradiate need to be loaded.

## Configuration file

N/A

## System configuration

- Operating system: MacOS, MacOS+Docker, Ubuntu, Ubuntu+Docker
- Compiler: clang++
- Python version: 3.7.10 Anaconda
- Eradiate version: 0.0.1

**Comment by nollety** [comment]
Thanks for reporting this issue @wint3ria 
I was able to reproduce the issue, I'll look into a fix as soon as possible.

**Comment by nollety** [comment]
I think I just found out where the issue is coming out. For some reason, a netcdf file was replaced with a file with the wrong format (most probably a mistake of mine during the last data set update). I checked the remaining files and they seem alright.
I'll re-upload the data set archive file to the eradiate ftp server.

**Comment by nollety** [comment]
@wint3ria The upload is completed; you can download the new archive file [here](https://eradiate.eu/data/spectra-us76_u86_4.zip). Let me know if the test still fails 😃

**Comment by wint3ria** [comment]
@nollety I'm checking this ASAP. Do you think it is possible that another file is corrupted? I'm not sure all the files are tested in the different Eradiate tests

**Comment by wint3ria** [comment]
@nollety I think you added some __MACOSX folders to your archives:
```
...
 inflating: spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/us76_u86_4_81372.7_276.37.nc
  inflating: __MACOSX/spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/._us76_u86_4_81372.7_276.37.nc
  inflating: spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/us76_u86_4_653.493_234.03.nc
  inflating: __MACOSX/spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/._us76_u86_4_653.493_234.03.nc
  inflating: spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/us76_u86_4_15.7106_240.33.nc
  inflating: __MACOSX/spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/._us76_u86_4_15.7106_240.33.nc
  inflating: spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/us76_u86_4_0.729222_194.42.nc
  inflating: __MACOSX/spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/._us76_u86_4_0.729222_194.42.nc
  inflating: spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/us76_u86_4_1.13067_199.47.nc
  inflating: __MACOSX/spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/._us76_u86_4_1.13067_199.47.nc
  inflating: spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/us76_u86_4_1571.06_224.71.nc
  inflating: __MACOSX/spectra/absorption/us76_u86_4/spectra-us76_u86_4-13000_13500/._us76_u86_4_1571.06_224.71.nc
...
```

**Comment by nollety** [comment]
At the moment, not all netcdf files are covered by eradiate tests, only a subset. I was thinking to add a test that would check all files indeed, that would be nice.

**Comment by nollety** [comment]
Arg, sorry about the __MACOSX folders, let me try to clean the archive file. I'll re-upload it shortly!

**Comment by nollety** [comment]
The issue has been resolved.
Thanks again @wint3ria for reporting this bug and sorry for the inconvenience.
